[package]
name = "merlang"
version = "0.1.0"
authors = ["catapillie"]
description = "mer programming language"
edition = "2021"

[[bin]]
name = "mer"
path = "src/mer.rs"

[dependencies]
byteorder = "1.5.0"
colored = "2.0.4"
pico-args = "0.5.0"
